"""
2023/10/30: Total card numbers: 116
2024/04/02: Total card numbers: 125
"""
# elixir2card = {
#   1: [
#     'ice-spirit',
#     'ice-spirit-evolution',
#     'skeletons',
#     'skeletons-evolution',
#   ],
#   2: [
#     'ice-golem',
#     'the-log',
#   ],
#   3: [
#     'cannon',
#   ],
#   4: [
#     'fireball',
#     'hog-rider',
#     'musketeer',
#   ],
# }
elixir2card = {
  -1: [
    'mirror',
  ],
  1: [
    'electro-spirit',
    'fire-spirit',
    'heal-spirit',
    'ice-spirit',
    'ice-spirit-evolution',
    'skeletons',
    'skeletons-evolution',
  ],
  2: [
    'barbarian-barrel',
    'bats',
    'bats-evolution',
    'bomber',
    'bomber-evolution',
    'giant-snowball',
    'goblins',
    'ice-golem',
    'rage',
    'spear-goblins',
    'the-log',
    'wall-breakers',
    'wall-breakers-evolution',
    'zap',
    'zap-evolution',
  ],
  3: [
    'archers',
    'archers-evolution',
    'arrows',
    'bandit',
    'cannon',
    'clone',
    'dart-goblin',
    'earthquake',
    'elixir-golem',
    'firecracker',
    'firecracker-evolution',
    'fisherman',
    'goblin-barrel',
    'goblin-gang',
    'guards',
    'ice-wizard',
    'knight',
    'knight-evolution',
    'little-prince',
    'mega-minion',
    'miner',
    'minions',
    'princess',
    'royal-delivery',
    'royal-ghost',
    'skeleton-army',
    'skeleton-barrel',
    'tombstone',
    'tornado',
  ],
  4: [
    'baby-dragon',
    'battle-healer',
    'battle-ram',
    'battle-ram-evolution',
    'bomb-tower',
    'dark-prince',
    'electro-wizard',
    'fireball',
    'flying-machine',
    'freeze',
    'furnace',
    'goblin-cage',
    'goblin-drill',
    'golden-knight',
    'hog-rider',
    'hunter',
    'inferno-dragon',
    'lumberjack',
    'magic-archer',
    'mighty-miner',
    'mini-pekka',
    'mortar',
    'mortar-evolution',
    'mother-witch',
    'musketeer',
    'night-witch',
    'phoenix',
    'poison',
    'skeleton-dragons',
    'skeleton-king',
    'tesla',
    'tesla-evolution',
    'valkyrie',
    'valkyrie-evolution',
    'zappies',
  ],
  5: [
    'archer-queen',
    'balloon',
    'barbarians',
    'barbarians-evolution',
    'bowler',
    'cannon-cart',
    'electro-dragon',
    'executioner',
    'giant',
    'goblin-hut',
    'graveyard',
    'inferno-tower',
    'minion-horde',
    'monk',
    'prince',
    'ram-rider',
    'rascals',
    'royal-hogs',
    'witch',
    'wizard',
  ],
  6: [
    'barbarian-hut',
    'elite-barbarians',
    'elixir-collector',
    'giant-skeleton',
    'goblin-giant',
    'lightning',
    'rocket',
    'royal-giant',
    'royal-giant-evolution',
    'sparky',
    'x-bow',
  ],
  7: [
    'electro-giant',
    'lava-hound',
    'mega-knight',
    'pekka',
    'royal-recruits',
    'royal-recruits-evolution',
  ],
  8: [
    'golem',
  ],
  9: [
    'three-musketeers',
  ],
  10: []
}

unit2cards = {
  'skeleton': ['skeletons', 'skeleton-army'],
  'skeleton-evolution': ['skeletons-evolution'],
  'ice-spirit': ['ice-spirit'],
  'ice-spirit-evolution': ['ice-spirit-evolution'],
  'hog-rider': ['hog-rider'],
  'musketeer': ['musketeer', 'three-musketeers'],
  'cannon': ['cannon'],
  'fireball': ['fireball'],
  'the-log': ['the-log'],
  'ice-golem': ['ice-golem'],
}

card2elixir = {c: elixir for elixir, cs in elixir2card.items() for c in cs}
card_list = list(card2elixir.keys())
idx2card = dict(enumerate(card_list))
card2idx = {c: i for i, c in idx2card.items()}

if __name__ == '__main__':
  print("Total card number:", len(card_list))
  print(idx2card)
  print(card2idx)
